### ISSUE TITLE
Does it make sense to have more than one multisynape buffers?

### ISSUE THREAD

**Issue by DimitriPlotnikov** [nest/nestml#190]
How can the following buffer declaration be interpreted:

```
 input:
    spikes1[receptors]   <- spike
    spikes2[receptors]   <- spike
    currents <- current
  end
```

Or the following situation valid?

```
input:
    spikes1[receptors]   <- excitatory spike
    spikes2[receptors]   <- inhibitory spike
    currents <- current
end
```

**Comment by Silmathoron** [comment]
@heplesser this looks related to the question we ran into regarding the "one buffer per rport" choice for multisynaptic neurons and the problem of the synaptic weight depending on the synapse type (current- vs conductance-based).
Maybe the NestML workshop would be a good time to discuss that kind of thing and we should put up a "design questions" agenda  on the wiki?

**Comment by DimitriPlotnikov** [comment]
@Silmathoron Great idea! Therefore, we organize it. @heplesser Are you going to join?

**Comment by heplesser** [comment]
@DimitriPlotnikov @Silmathoron Unfortunately, I won't be able to participate the NESTML workshop.

For current policy in NEST, see the [Design Decision reached in the 19 Sep 2016 ODVC](https://github.com/nest/nest-simulator/wiki/2016-09-19-Open-NEST-Developer-Video-Conference).

We have four different situations concerning the routing of incoming spikes:

1. Implicit routing based on sign of weight
1. Explicit routing to one of many equivalent, enumerated synapses
1. Explicit routing to one of several different, names synapses
1. A combination of the above

## 1. Implicit routing based on sign of weight
This applies to standard neurons with one excitatory and one inhibitory synaptic time constant, `tau_syn_ex` and `tau_syn_in`. Spikes with non-negative weights are added to the buffer feeding the synapse with time constant `tau_syn_ex`, spikes with negative weights to the buffer feeding the synapse with time constant `tau_syn_in`. Could/should NESTML make this explicit, e.g., something like
```
spikes[tau_syn_ex] <- spike : w >= 0
spikes[tau_syn_in] <- spike : w < 0
```

## 2. Explicit routing to many equivalent, enumerated synapses
This applies to all `_multisynapse` neuron models. After the design decision of 16 Sep 2016, you have exactly one input channel per synaptic time constant. The input channel must be addressed explicitly by given a `receptor_type` (aka `rport`). Could one use a notation such as
```
spikes[receptor_type] <- spike : receptor_type
```
`receptor_type` would have to be a reserved word here, and it is a bit unfortunate that it is only implicit in that reserved word that there is more than one spike input buffer. For conductance-based synapses, there is also a different reversal potential for each receptor type, which is not obvious from the notation above.

## 3. Explicit routing to one of several different, names synapses
This applies at present mainly to the `ht_neuron`, but see also the multicompartment variant of the iaf neuron. Here, we have a small number (4 for ht) of synapses with, in part, very different dynamics. These synapses should be named, not enumerated, to make the nature of the input dynamics explicit to the user. In this case, a `receptor_types` dictionary tells the user which channels are available and to which receptor types they are matched. In NESTML, maybe one could do something like
```
receptor_types <- AMPA, NMDA, GABA_A, GABA_B

spikes[receptor_type] <- spike : receptor_type
```

## 4. Other cases
Precise neurons are more problematic, since they place all spikes in a single buffer and then differentiate at the time spikes are read from that buffer, causing some problems of its own, e.g., NEST issue 368.

**Comment by DimitriPlotnikov** [comment]
Dear, @heplesser thank you for your feedback!

1) ready. But instead of w <= 0 and w => 0 I use keyword `inhibitory` and `excitatory`. On the one hand w notation is rather technical. On the other hand I don't know if it also matches the conductance case. Finally, how could you express a model with one buffer (cf. https://github.com/nest/nestml/blob/master/models/iaf_neuron.nestml)
Current syntax for this:
  input:
    ex_spikes   <- excitatory spike
    in_spikes   <- inhibitory spike
end

2) I'll evaluate it. I don't like how I currently implemented it (cf. https://github.com/nest/nestml/blob/master/models/iaf_psc_alpha_multisynapse.nestml)

3) Currently I implemented a slightly different notation:
input:
      AMPA   <- spike
      NMDA   <- spike
      GABA_A <- spike
      GABA_B <- spike
      currents <- current
end
From this definition, NESTML generates the NEST API with receptor_types from it. You proposal would be also an option, but it sound rather technical for me.

**Comment by abigailm** [comment]
Hi, I really recommend talking to Renato before converging to a solution. As far as I am aware, he is one of the few people routinely using these models in production and he may have some insights into limitations of the current approach that should be taken into consideration.

**Comment by clinssen** [comment]
Discussion continued in #944.
