### ISSUE TITLE
Computation of unit magnitudes

### ISSUE THREAD

**Issue by DimitriPlotnikov** [nest/nestml#291]
Test to reproduce: org.nest.integration.NestmlFrontendIntegrationTest#testTutorialModels

Produces the following warnings:
`
32_rc_alpha : WARNING: NESTML_ODEPostProcessingVisitorType of (derived) variable g_ex'' is: A * s**-1 * Ts**-1. This doesnt match Type of RHS expression: A * s**-1 * Gs**-1 at: 32_rc_alpha.nestml:<14,4>
`
I would like to clarify 2 questions
1) I don't understand the meaning of the term `s**-1 * Gs**-1`. Both are seconds?
2) How should the equation look like to be accepted
3) Should we make the type checking parameterizable in the sense that magnitude check (only the type signature without is considered) can be turned off?

@PTraeder what is you opinion?

**Comment by PTraeder** [comment]
1.: Is mostly related to shortcomings in the formatting for unit names. 
An overhaul of that system is pending.

A * s**-1 * Ts**-1  is the formatted name for [0,-2,0,0,0,0,1,-12] (more readable this would be "nA/s**2")
A * s**-1 * Gs**-1 is the formatted name for [0,-2,0,0,0,0,1,-9] (or rather "pA/s**2")

They are different units in terms of magnitude only. The prettyPrinter currently dumps all magnitude information in the last matched unit name ( in this case -12 and -9 are dumped into the "s" factor wich has a negative exponent resulting in Giga and Terra prefixes rather than nano and pico).

There are a few improvements I can implement to the formatting system to make things more readable.


2.: These errors are usually remedied by juggling around the types involved. In this case changing the type of tau_syn from ms to s in line 24 would do the trick.

This, it occurs to me while writing, is due to a bug where "deriving" does not take into account the types involved in the associated ODE. It should be an easy fix to include magnitude information from the ODE when calculating the type of the "derived" variable.

3.:Yes. But its probably not needed if the bug in (2) is solved?

**Comment by PTraeder** [comment]
Actually, fixing (2) requires changes to how we assign symbols for derived variables. See Issue#299

**Comment by PTraeder** [comment]
PR #304 ignores magnitude checks for expressions containing "derived" variables. This (stopgap) avoids (2)

**Comment by Silmathoron** [comment]
Actually this is a bug that still occurs in NESTML: currently, processing the ``.nestml`` models leads to errors like

    Addition/substraction of 1 / nH and 1 / muH. Assuming real.

Whereas terms with same unit but different magnitudes should be automatically converted to:
* the unit of the container if it is the same (e.g. ``g = a + b`` where ``a = 10 nS`` and ``b = 1 muS`` should be interpreted as ``g = 1010 nS`` since the unit of ``g`` is ``nS``)
* the coherent unit in the NEST system if the container has another unit (e.g. ``I = g1*(V1 - E1)``, where ``g`` is in ``nS``, ``V1`` is in ``V`` and ``EL`` is in ``muV`` should convert both ``V1`` and ``E1`` to ``mV`` since ``mV*nS`` gives ``pA``, which is the relevant unit for currents in NEST.

**Comment by PTraeder** [comment]
Expressions dont allow me to check where they are used when they are checked. Furthermore such a check would either be very restrictive ( only for assignments of the form g = a+b) or it would need to handle additions deep inside another expression as well, and at that point the "container type" is not defined.

**Comment by PTraeder** [comment]
We could, when the switch to errors instead of warnings occurs, include an option to disable magnitude checks everywhere in the model ( currently they are only disabled for ODEs )

**Comment by Silmathoron** [comment]
From what I discussed earlier today with @DimitriPlotnikov, I think one point to consider would simply be to force users to use the units that are coherent with NEST for state variables:
``mV, nS, ms, pA, pF...``
This way the problem of magnitude check would not be hard: you simply convert any parameter or other constant to the relevant NEST magnitude.

**Comment by PTraeder** [comment]
Will discuss with @DimitriPlotnikov and get back to you.

**Comment by clinssen** [comment]
Closing this as it pertains to a very old version of NESTML; in addition, the units system has been thoroughly overhauled since then. Please open a new issue with a minimal working example if it persists.
