### ISSUE TITLE
No "nestml" user docker image

### ISSUE THREAD

**Issue by Silmathoron** [nest/nestml#315]
With latest master, docker installation runs fine, but when using ``docker run [options] nestml_release``, I get the following error:

    adduser: invalid number '-D'
    sudo: unknown user: nestml
    sudo: unable to initialize policy plugin

I guess the ``nestml`` user was not created, but I have no idea what went wrong... my guess is that it's the ``$UID`` in ``entrypoint.sh`` but I'm not sure.
I manually changed it to ``adduser -D nestml``, which seems to work.

**Docker:** 1.12.3
**System:** Manjaro (Arch-based)

**Comment by jougs** [comment]
Can you please try running our script `nestml_docker.sh` like this:
```
./nestml_container.sh provision # Create the container
./nestml_docker.sh run <modeldir> # Run the container
```
We had some trouble with running the container on multi-user systems, which we fixed by that wrapper script, which passes the current user's UID into the container and an entrypoint script, which  creates a new user inside the container with a corresponding UID.

As a consequence, the container probably fails if you run it without the wrapper.

I'll update the README soon. Sorry for not doing so earlier.

**Comment by Silmathoron** [comment]
Ok, no problem, thanks for the fast answer.
This works like a charm.
