### ISSUE TITLE
Is it possible to compile in one PC and install the build directory in another one?

### ISSUE THREAD

**Issue by hyukz** [nest/nestml#393]
Greetings everyone,

I have successfully installed and used NESTML in my personal computer, but as I want to try new simulations of my model in our laboratory's cluster, I was thinking whether it was possible to do so without installing NESTML on said computer and re-compiling everything.

I have tried so but, and after cmake / make / make install (with no errors), I tried to load my model both in SLI and PyNEST and I get an error as the following: 

`Nov 17 15:04:25 Install [Error]: DynamicModuleManagementError`
`Module 'mat2_cond_exp' could not be opened.`
`The dynamic loader returned the following error: 'file not found'.`
    
`Please check LD_LIBRARY_PATH (OSX: DYLD_LIBRARY_PATH)!`

Now, my `nest_vars.sh` is already exporting my user model directory (`export NEST_MODULE_PATH=$NEST_INSTALL_DIR/lib64/nest`), and I've also manually added that directory to `LD_LIBRARY_PATH` without success. As expected, this directory includes two files: `libmat2_cond_exp.so` and `mat2_cond_exp.so`.

After trying many different things, I wondered whether during compilation, NESTML uses the paths of the current PC/current NEST installation to index something in the compiled code, and if a conflict could be occurring when I copied only the `build` folder to a new PC and tried to run it there.

Thank you very much for your attention.

P.S.: Besides avoiding the process of installing NESTML everywhere I want to use it, I am particularly interested in this topic because as I want to share my studies in the future, I don't want to force prospective users to install both NEST and NESTML, as the latter's installation is not trivial currently

**Comment by jougs** [comment]
GitHub is meant as an issue tracker for bugs and technical problems with NESTML and NEST. Because of this, only a very limited amount of people (those who actively chose to monitor it) are notified of activities here.

For discussions of this kind, we have the [NEST User Mailing List](http://www.nest-simulator.org/community/). May I kindly ask you to subscribe and re-post your question there so that all users can see the question and answers? I'll happily answer if you do.
