### ISSUE TITLE
Why duplicate units in declarations?

### ISSUE THREAD

**Issue by vogdb** [nest/nestml#401]
Can we use `E_L mV = -55` instead of `E_L mV = -55mV`?
Now I have a problem with Ideal Gas Constant `R` in *parameters* block:
```
  parameters:
    t_ref ms = 2.0ms         # Refractory period
    ...
    R_const (kg*m**2)/(s**2*K*mol) = 8.314472[(kg*m**2)/(s**2*K*mol)]
  end
```
I receive an **error**
```json
[ {
  "filename" : "hh_moto_5ht.nestml",
  "neuronName" : "",
  "severity" : "ERROR",
  "code" : "NESTML_PARSER",
  "row" : 121,
  "col" : 42,
  "message" : "mismatched input '[' expecting {'end', 'and', 'or', 'recordable', 'function', '**', '<<', '>>', '<=', '<>', '^', '==', '[[', '%', '&', '*', '+', '-', '/', '|', '<', '!=', '>', '>=', '?', Name, NEWLINE}"
} ]
```
I don't receive an error in either of cases below
```
  parameters:
    R_const (kg*m**2)/(s**2*K*mol) = 8.314472 * ((kg*m**2)/(s**2*K*mol))
  end
```
```
  parameters:
    R_const (kg*m**2)/(s**2*K*mol) = 8.314472
  end
```

**Comment by DimitriPlotnikov** [comment]
We don't support the syntax with `[...]` anymore.
@PTraeder why don't we get an error in the:
```
parameters:
    R_const (kg*m**2)/(s**2*K*mol) = 8.314472
 end
```

**Comment by kperun** [comment]
@vogdb The error regarding
`parameters:
    R_const (kg*m**2)/(s**2*K*mol) = 8.314472
 end
`
was a part of the deprecated Java implementation of NestML. In PyNestML, this error is reported as the following:
`
[12,expressionType_test, ERROR, [58:41;58:41]]: Actual type different from expected. Expected: 'kg m2 / (K mol s2)', got: 'real'!
`
As Dimitri mentioned, the syntax with [...] is not supported in PyNestML. The repetition of units is intended, otherwise, the underlying tool-chain would not be able to understand whether it is a typing error or intended by the user (i.e., whether the user really provided a unit-less constant or a constant with an implicit unit mV). 

I will close this issue since it is no longer relevant. If you have any questions just open a new one.
