### ISSUE TITLE
How to make state variables accessible in Status dictionary of neuron model

### ISSUE THREAD

**Issue by mschmidt87** [nest/nestml#407]
Hi,

I am trying to compile a neuron model with two state variables. I initialize the state variables in an `initial_values` block and then define their time evolution in an `equations` block. I then expected these state variables to appear in the Status Dictionary of the neuron model in PyNEST. That is, I would like to set their value manually by executing
`SetStatus(neuron, {'v': -60., 'g_k': 0.})`

However, the state variables do not appear in the status dictionary when I call 
`GetStatus(neuron)` and I cannot set them using the command above, and I receive the usual error message

> NESTError: DictError in SetStatus_id: Unused dictionary items: v g_k

Do I have to define these state variables differently or how does this work?
Thanks.

**Comment by mschmidt87** [comment]
What I found out:
If I put the state variable in the `state` block instead of the `initial_values` block, NESTML complains that 

> The variable has to be defined in the 'initial_values' block for being unsed on the left side of an ODE

Putting the variable in both blocks (`initial_values` and `state`) leads to the error:

> The variable is defined multiple times

So, how to make sure that a state variable that is governed by an ODE enters the state dictionary?
By the way: The `initial_values` is not documented in doc/syntax.md .

**Comment by mschmidt87** [comment]
Another finding: Looking into the generated C++-Files, we found that the `get_v` and `set_v` Function exists, but it does not appear in the `set_status` Function.

**Comment by kperun** [comment]
@mschmidt87 
To put it simply: It's a missing feature which I will include in one of the next updates of PyNestML.
Explanation: The initial_values is something new which has been added not that long ago, thus several features for code generation has not yet been updated to support the generation of these properties. NestML error messages are correct: by declaring the variable in both, it leads to a redeclaration. Otherwise, if you put it only in the state block, the ODEs are not provided with any starting values. So it is correct to simply state those variables in the init values block. 
I will fix the problem of missing get/set in the get_status/set_status and update this ticket here to inform you.

**Comment by kperun** [comment]
@mschmidt87 
I have updated PyNestML and included this feature. Until it is merged into the official branch, feel free to use this one:
https://github.com/kperun/nestml/tree/stable_PyNestML

set_status and get_status now also include everything to access the variables of the initial values block. So you can use  SetStatus(neuron, {'v': -60., 'g_k': 0.}) where v is an initial values variable. If there are any bugs, please report them.
Best regards
Konstantin

**Comment by kperun** [comment]
Issue closed, since set_status for initial values has been integrated into the master branch.
