### ISSUE TITLE
New mechanism for refractoriness

### ISSUE THREAD

**Issue by clinssen** [nest/nestml#439]
Refractoriness exposes the timestep of the simulator (see e.g. https://github.com/nest/nestml/blob/16f4cdab6e3b4a8461db300a3490ac5e03c346d1/models/aeif_cond_alpha.nestml#L94). Ideally this would be refactored in a more simulator-agnostic way (where the user specifies only a time period of refractoriness, not a number of steps). This, in turn, might require some new language constructs. The purpose of this issue is to collect ideas about what this could look like!

**Comment by Silmathoron** [comment]
Hi @clinssen, as promised, I am back on NESTML after a long absence ^^
I totally agree with the necessity of making a refractory time to replace the current count.
I am not sure I see where the problem lies, though: naively, I would think that we just need to convert it to ``ms`` and warn the user on the fact that, NEST being grid-based, the refractory time will be cut to the nearest value (for precise models, if they are supported, just use the existing refractory event).

Tthe conversion from duration to steps can be done as usual in ``calibrate``, no? What am I missing?

**Comment by clinssen** [comment]
Closing as "not an issue!"
