### ISSUE TITLE
"current" input is missing physical units

### ISSUE THREAD

**Issue by clinssen** [nest/nestml#450]
e.g.:

    input:
        AMPA nS  <- spike
        currents <- current
    end

**Comment by kperun** [comment]
@clinssen According to my (rather limited) understanding, current inputs are allways of the same physical unit, namely pA (if I remember it correctly). We, therefore, did not integrate a concept for the specification of a physical unit.

**Comment by clinssen** [comment]
Thanks for providing the background rationale! I would still propose to specify the units explicitly, because otherwise we'll have to document somewhere what the default is, and make the user search for that bit of documentation. It would also add to the expressiveness of the language just in case the user wants a unit other than pA.

**Comment by kperun** [comment]
@clinssen In this case, you can just reuse the rule for the spike input, since only the keyword (and some minor details in the classes) differ. Previously, we explicitly distinguished between current and spike inputs (since only the spikes could be of a different physical unit, while currents were always of type pA). Buf if you think that the there exists some kind of benefit, you can also adjust the rule for current.

**Comment by jougs** [comment]
I would also like it if the unit were explicitly specified. Even if it was `pA` in all models. Just my two cents.
