### ISSUE TITLE
Handling delta function properly

### ISSUE THREAD

**Issue by clinssen** [nest/nestml#492]
The NESTML predefined `delta` function, which is used in convolve calls, has two parameters: time and a time constant. It does not make sense for a delta function to be parameterised by a time constant. This constant is apparently assumed to be equal to the time constant of the membrane potential ODE in https://github.com/nest/nestml/blob/73f484e260d8026796c610e21f727b6c52ac360d/pynestml/solver/solution_transformers.py#L76

`ode_var_update_instructions` is e.g. 
```py
V_abs = V_abs * exp(-__h / tau_m)
V_abs += (tau_m / C_m - tau_m * exp(-__h / tau_m) / C_m) * (I_e + currents - w)
V_abs += spikes
```
Note the `tau_m` in the first line, which comes from the NESTML model specification `shape G = delta(t, tau_m)` in iaf_psc_delta (which is apparently the only model included that uses the delta function).

**Comment by Silmathoron** [comment]
I'll detail here a proposed workflow to handle the delta function properly.

1. Remove the second parameter
2. Remove [special case in NESTML](https://github.com/nest/nestml/blob/master/pynestml/codegeneration/nest_codegenerator.py#L292) (not working anyway)
2. Update [``ode-toolbox``](https://github.com/nest/ode-toolbox) so that it handles the delta function as any other shape

**Proposed NESTML update:**
Make NESTML correctly grabs and stores the ``delta`` shape in [transform_shapes_and_odes](https://github.com/nest/nestml/blob/master/pynestml/codegeneration/nest_codegenerator.py#L272) and the [json transform](https://github.com/nest/nestml/blob/master/pynestml/codegeneration/nest_codegenerator.py#L355) so they are properly [passed](https://github.com/nest/nestml/blob/master/pynestml/codegeneration/nest_codegenerator.py#L352) to [analysis' ``indict``](https://github.com/nest/ode-toolbox/blob/master/odetoolbox/__init__.py#L70).

**Proposed ode-toolbox update:**

1. give ode-tools' [``shapes_from_function``](https://github.com/nest/ode-toolbox/blob/master/odetoolbox/shapes.py#L119) access to the ODEs [here](https://github.com/nest/ode-toolbox/blob/master/odetoolbox/__init__.py#L100)
2. convert strings containing ``delta`` in [``shapes_from_function``](https://github.com/nest/ode-toolbox/blob/master/odetoolbox/shapes.py#L119) to [``DiracDelta``](https://docs.sympy.org/0.7.2/modules/functions/special.html#diracdelta) so that sympy can parse it properly
3. make a special case ``if`` before the [linear homogeneous ODE test](https://github.com/nest/ode-toolbox/blob/master/odetoolbox/shapes.py#L199) because the delta function obviously does not respect this condition
4. in that ``if`` block, use the ODE passed to find the state variable to which the delta function must be applied. This should give ``S^(n) = whatever + delta``, with ``S^(n)`` being the ``n``th derivative of the state variable `S`. The jump will thus occur on ``S^(n-1)`` (typically with ``V_m'`` and ``V_m`` for standard delta synapses.
5. wrap all this properly into the nice [``solver_result`` dict](https://github.com/nest/nestml/blob/master/pynestml/codegeneration/nest_codegenerator.py#L301) passed to [``functional_shapes_to_odes``](https://github.com/nest/nestml/blob/master/pynestml/solver/solution_transformers.py#L110), then to[``_convert_to_shape_specific``](https://github.com/nest/nestml/blob/master/pynestml/solver/solution_transformers.py#L148) has the proper content:

```python
{
     'solver': 'numeric',
     'shape_ode_definitions': [],
     'shape_state_variables': ['S', ..., 'S^(n-1)', 'S^(n)'],
     'shape_initial_values': ['0', ..., '1', '0'],
}
```
