### ISSUE TITLE
Make ``internals`` block parsed first?

### ISSUE THREAD

**Issue by Silmathoron** [nest/nestml#510]
Currently, when using the ``internals`` block, the block must be placed above the first block which makes use of the variables declared in it, so my guess is that blocks are parsed sequentially.
However, the ``internals`` block is not very important and it's annoying to have it before more relevant blocks... how difficult would it be to parse it first?
(if I remember correctly we're parsing tree so it should be trivial, but I just want to make sure)

**Comment by Silmathoron** [comment]
Ok, I just realized why that cannot be done:

```
internals:
  RefractoryCounts integer = steps(t_ref) # refractory time in steps
end
```

That's annoying though, it would be nice to see whether we could delay definition check until both ``parameters`` and ``internals`` have been checked... could we draw a dependency graph and use it to order the parameters and internals properly so that everyone is defined after their dependencies (and only then throw an error if that's not possible)?

**Comment by Silmathoron** [comment]
"Upping" this issue for two (OK, one and a half) reasons:
1. this issue is bound to happen for many users and they may not understand why NESTML is suddenly crashing when they use an internal variable in ``equations`` with ``internals`` below ``equations``
2. as users start using NESTML to generate their models, they may want to speed things up (e.g. removing all divisions) which requires the ``internals`` block

**Comment by clinssen** [comment]
I'm not sure whether I looked into ordering of blocks specifically, but I am having trouble reproducing the issue on the ode-toolbox changes feature branch (https://github.com/clinssen/nestml/tree/ode-toolbox-integration, see #515). I'm testing on that branch because there were many changes, and it will be the basis for NESTML going forward. Could you see if things work for you as expected there, and otherwise post a minimal example that reproduces the issue? Cheers!
