### ISSUE TITLE
Using NESTML with repo-based NEST and Boost

### ISSUE THREAD

**Issue by Silmathoron** [nest/nestml#542]
We now have a bunch of pre-built NEST from repo (see [install](https://nest-simulator.readthedocs.io/en/stable/installation/index.html)).
However, at least for the ubuntu package, the source files are not included in a way that  is automatically detected by the NESTML install script (though for ubuntu it is ``/usr/include/nest``).
Since these installation methods are likely to become dominant, I think we need to address this issue.
Similar problem arises if NEST is compiled with ``-Dwith-boost=1`` as the include path is not contained automatically; this option will become default in NEST3.

Steps to reproduce: build a model with default NESTML config with a prebuilt NEST or with a NEST built with Boost.

Potential link to #480 and #503

**Comment by jougs** [comment]
@clinssen: Can this issue be solved in NESTML directly, or should it rather be addressed by changes to the `nest-config` script? Thanks!

**Comment by clinssen** [comment]
@Silmathoron: sorry for the late reply. Could you report the output of `nest-config --includes`?

**Comment by Silmathoron** [comment]
Not right now, unfortunately, I'm not a Debian user, but I'll try to do it soon.
Is Boost supposed to be in there too (do I need to provide it for the self-compiled install with boost)?

**Comment by clinssen** [comment]
I believe NEST is receiving some updates right now related to Boost. Please hold tight until https://github.com/nest/nest-simulator/pull/1502 and https://github.com/nest/nest-simulator/pull/1477 are merged.

**Comment by tfardet** [comment]
Hey there, additional question regarding the use of NESTML with deb-repo NEST: it seems that ``install_nest`` would typically then try to install to the system location after calling the NEST config files, which of course leads to a permission error.
Is there currently a way to address this or a plan to fix it in the near future or does NESTML only work with local builds?
Asking because I'm getting questions from people that used the Ubuntu PPA and now try to use NESTML.

**Comment by jougs** [comment]
Dear @tfardet, I am not fully convinced by the workaround and think the proper solution is to actually support the CMake switch `-DCMAKE_INSTALL_PREFIX` in the NESTML generated NEST extension module.

Currently, we just overwrite the prefix by whatever we get from `nest-config`. If we would just check if the user set a different location and use that value instead, users could install to arbitrary locations and then set `LD_LIBRARY_PATH` before running NEST.

I'm not yet completely sure how to handle `install_nest` in this situation, but think this should also be possible without too much hassle.

**Comment by tfardet** [comment]
Hi @jougs yeah, actually I tried the potential workaround but it does not work anyways, and it's definitely not a long-term solution.
Since I don't think there's any reasonable way to install to ``/usr``, I would propose to default to ``$HOME/.local`` if NEST has been installed system-wide with an optional parameter to override this if the user wants.
Maybe a note somewhere warning users about using NESTML with system-wide NEST installs in the meantime?

**Comment by jougs** [comment]
I'm working on this today and am somewhat confident to have a fix by tonight.
