### ISSUE TITLE
NESTML module installation failed to load /usr/include/nest

### ISSUE THREAD

**Issue by kingshukchakravarty2** [nest/nestml#674]
I have installed pre-built NEST and NESTML from repo 
(followed apt install -- https://nest-simulator.readthedocs.io/en/stable/installation/index.html -- for nest installation
followed pip install -- https://nestml.readthedocs.io/en/latest/installation.html).
However, while installing a NESTML example module, the source files are not included in a way that is automatically detected by the NESTML install script (though for ubuntu it is /usr/include/nest).
output of 
===============================
nest-config --includes
 -Idebian/nest/usr/include/nest -I/usr/include -I/usr/include -I/usr/include
===============================
I am not sure whether this issue is to be solved in NESTML directly, or  it should rather be addressed by changes to the nest-config script. 

Note that my python version -- Python 3.8.5
NEST version -- nest-2.20.1

Could you pleas help me solve this issue?

**Comment by clinssen** [comment]
Hi, thanks for writing in!

The latest NESTML version generates code that is unfortunately not compatible with NEST 2.20.1, but this should be fixed very soon, see #672.

It looks like you installed NEST Simulator into ``/usr``, so to install the NESTML generated module in that same directory, you need to have the right permissions. Probably this simply means you have to do a "sudo make install" rather than just "make install" in the target directory.

If you are not running "make install" manually in the command line, but are using the to_nest() and install_nest() Python API, it means you will either have to do the "make install" step manually (and add sudo), or run the whole script (the one with the install_nest() call in it) as sudo/root.

**Comment by clinssen** [comment]
Closing assuming this is solved. Please let us know otherwise!
