### ISSUE TITLE
NESTML homepage has some unreadable characters

### ISSUE THREAD

**Issue by pnbabu** [nest/nestml#736]
The bullet points on the home page are displayed as some unreadable characters. See below.

<img width="394" alt="image" src="https://user-images.githubusercontent.com/75320801/157931480-1688231d-5558-4d60-8246-7e7580be3b6d.png">

**Comment by clinssen** [comment]
Probably, your browser chooses a font that does not include these characters. (For me, the font is "Lato".) I'd also prefer to have normal bullet points here, as in your PR, but there is something that makes these lists render without bullet points. Please double-check the render on RtD: https://nestml-sandbox.readthedocs.io/. I believe there is an inconvient rule in ``theme.css`` that applies to unordered lists. We could possibly override this in ``custom.css`` on our side, using the CSS keyword ``!important``.

When the bullet points come back, please also reformat the tutorials list into not being an actual list, so that the current formatting as-rendered is preserved. Cheers!

**Comment by pnbabu** [comment]
My browser also has the font Lato. I even checked in Firefox and I could see the same characters.
The normal bullet points look fine in my RtD build: https://nestml-doc.readthedocs.io/en/latest/, both in Chrome and Firefox.

**Comment by clinssen** [comment]
For some reason, my RtD build was stuck on an old version for the package ``sphinx_rtd_theme``. Could you also add a ">=1.0.0" in ``doc/requirements.txt``?
