### ISSUE TITLE
synapse namespace assertion error in third_factor_stdp

### ISSUE THREAD

**Issue by Yanagar1** [nest/nestml#782]
Maybe similar to this issue? https://github.com/nest/nestml/issues/703

I'm installing nestml with miniconda and running the ipython instructions [here](https://nestml.readthedocs.io/en/latest/installation.html)
nest-simulator            3.3    
nestml                    5.0.0

output:

Generating code for the synapse third_factor_stdp.
in nest_code_generator.py:922
assert len(namespace["pre_ports"]) <= 1, "Synapses only support one spiking input port"

AssertionError: Synapses only support one spiking input port

**Comment by clinssen** [comment]
Hi, thanks for writing in! This may be due to (most) synapses having to be co-generated with the neuron they connect to in the NEST simulation. Please see https://nestml.readthedocs.io/en/latest/nestml_language/synapses_in_nestml.html#generating-code, and specifically the ``post_ports`` option described there. For examples on how to generate code for synapses, please see the unit tests for synapses in https://github.com/nest/nestml/tree/master/tests/nest_tests.
